### ISSUE TITLE
Unable to back out of the Settings screen

### ISSUE THREAD

**Issue by mjfwebb** [JumpyLionnn/enchanted-view#1]
**Describe the bug**
When I go to the Settings screen I am unable to return

**To Reproduce**
1. Go to Settings screen
2. Click on the back button
3. Nothing happens

**Expected behavior**
It takes me back to the main view

**Screenshots**
![image](https://github.com/JumpyLionnn/enchanted-view/assets/28074382/e6967fb9-8bf5-406d-baca-00abba5c6d5a)

**Comment by JumpyLionnn** [comment]
This bug is a stupid copy/paste error, in your case the button is disabled because you don't have an image loaded.
