### ISSUE TITLE
Open files from menu

### ISSUE THREAD

**Issue by mjfwebb** [JumpyLionnn/enchanted-view#2]
**Is your feature request related to a problem? Please describe.**
I would like to have a file -> open menu to open files from my filesystem

**Describe the solution you'd like**
A `File` menu with the `Open...` submenu item, which will present an operating system file management dialogue to find the file I want to load

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by JumpyLionnn** [comment]
The image viewer is intended to be set as the default image viewer. When it is the default image viewer you can just open an image. 
I am not sure I want to add this as the image viewer is not intended to be used that way. It might have some editing capabilities (like the windows image viewer) but nothing worth opening the app and then inside it opening a specific file, it would normally be the other way around.
I will think about it.
Thanks for the suggestion :)

**Comment by JumpyLionnn** [comment]
I have gotten a few requests for this, all in different ways.
I still think this app isn't suppose to be used like it(the image should opened using the app and not the other way around)
But I can see some uses for something like that.
I will add drag and drop image to view them and, you didn't load an image an additional button will appear below the error message to open the native file dialog.
What do you think?

**Comment by mjfwebb** [comment]
Sounds good to me!
